---
# tasks file for serverTools
- name: Criar artefatos em cada m치quina
  hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Configurar hostname de cada m치quina
      hostname:
        name: "{{ hostname }}"
      notify:
      - addInHostsFile
    - name: Atualizar o apt e instalar pacotes necess치rios
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - vim
          - iftop
          - curl
          - wget
          - python3
        state: present
      when: ansible_os_family == "Debian"

    - name: Atualizar o yum e instalar pacotes necess치rios
      yum:
      name:
        - vim
        - iftop
        - curl
        - wget
        - python3
      state: present
      when: ansible_os_family == "RedHat"  
  