---
- name: Criar artefatos em cada m치quina
  hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Configurar hostname de cada m치quina
      hostname:
        name: "{{ hostname }}"

    - name: Criar diret칩rio customizado
      file:
        path: "{{ default_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
    
    - name: Criar diret칩rios customizados
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      with_items:
        - " {{ dict_dir.scripts }}"
        - " {{ dict_dir.backups }}"
        - " {{ dict_dir.logs }}"
        - " {{ dict_dir.config }}"

    - name: Criar teste.py com touch e tempos personalizados
      ansible.builtin.file:
        path: "{{ default_dir }}/teste.py"
        state: touch
        modification_time: preserve
        access_time: preserve
        mode: '0644'
        owner: root
        group: root

 